version: '3.8'

services:
  web:
    build: .
    expose: 
    - "2000"
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    nginx:
      image: nginx:latest
      ports:
        - "2000:2000"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - web
  
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data

volumes:
  redis-data: 



    